module.exports =  {
    "ENV": {
        "LOC":"LOC",
        "DEV":"DEV",
        "TEST":"TEST",
        "PRO":"PRO"
    },
    "LOC":{
        "API":{
            "DNDC":"http://172.26.153.45/cbbweb",
            "E4Swap":"http://e4s.stg.dongfeng-nissan.com.cn/wap",
            "E4S":"http://e4s.stg.dongfeng-nissan.com.cn"
        },
        "CONTEXT_PATH":"http://127.0.0.1:3000",
        "ASSERT_PATH":"http://127.0.0.1:3333"
    },
    "DEV":{
        "API":{
            "DNDC":"http://172.26.153.45/cbbweb",
            "E4Swap":"http://e4s.stg.dongfeng-nissan.com.cn/wap",
            "E4S":"http://e4s.stg.dongfeng-nissan.com.cn"
        },
        "CONTEXT_PATH":"http://e4s.stg.dongfeng-nissan.com.cn/wap",
        "ASSERT_PATH":"http://e4s.stg.dongfeng-nissan.com.cn/wap/topic"
    },
    "TEST":{
        "API":{
            "CBB":"http://14.23.175.36/cbbweb",
            "LANYOU":"http://172.26.152.176/lanyou"
        },
        "CONTEXT_PATH":"http://127.0.0.1:3000",
        "ASSERT_PATH":"http://127.0.0.1:3333"
    },
    "PRO":{
        "API":{
            "E4Swap":"http://m.chebaba.com",
            "E4S":"http://m.chebaba.com"
        },
        "CONTEXT_PATH":"http://m.chebaba.com",
        "ASSERT_PATH":"http://m.chebaba.com/topic"
    }
};
